name: Lint and Test

# Controls when the action will run. Triggers the workflow on push or pull request on any branch
push:
  branches:
  - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  lint_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      # This tells GitHub Actions to use our docker image
      image: hawkeyesec/scanner-cli:latest
      # This tells GitHub Actions to mount the location where the code was checked out to /target
      options: -v /__w/as101-4-workshop/as101-4-workshop:/target

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: build docker containers
      run: |
        docker-compose build
    - name: Lint web using flake8 in web docker container
      run: |
        docker-compose run web bash -c \
          "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics \
           && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
    - name: Basic smoke test
      run: |
        docker-compose up --build --detach
        sleep 10
        curl --fail localhost:8000
